# Generated by Django 4.2.7 on 2023-11-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='username',
        ),
        migrations.AddField(
            model_name='register',
            name='name',
            field=models.CharField(default='ghj', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
