# Generated by Django 4.2.7 on 2023-11-21 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educapp', '0002_remove_register_username_register_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='registers',
        ),
    ]
