# Generated by Django 4.2.7 on 2023-11-21 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educapp', '0003_rename_register_registers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registers',
            old_name='name',
            new_name='username',
        ),
    ]
