# Generated by Django 4.2.7 on 2023-11-21 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('educapp', '0005_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logins',
        ),
    ]
