# Generated by Django 4.2.7 on 2023-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educapp', '0006_rename_login_logins'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phno', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('department', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
            ],
        ),
    ]
